### DISCUSSION TITLE
Range 组件

### DISCUSSION THREAD

**Discussion by oasis-cloud** [jdf2e/nutui-react#4] [General]
1. modelValue 设置为负数的时候 UI 显示不正常
2. touch-action:pan-y 只需设置到本组件
```css
* {
  touch-action: pan-y;
}
```
3.  删除无用代码和无用注释
