### ISSUE TITLE
修改主题色后，按钮禁用时的颜色没有根据主题色变化

### ISSUE THREAD

**Issue by zhangminggeek** [jdf2e/nutui-react#2327]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.8

### 平台

weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx

### 重现步骤

primary 类型的按钮背景色用的是
```css
  --nutui-color-primary-stop-1: var(--nutui-brand-stop-1);
  --nutui-color-primary-stop-2: var(--nutui-brand-stop-2);
```

禁用按钮用的颜色是一个另外的、单一的色值，失去了渐变效果

```css
--nutui-color-primary-disabled: var(--nutui-brand-3);

.nut-button-primary.nut-button-disabled {
    background: var(--nutui-button-primary-disabled, var(--nutui-color-primary-disabled, #fd9d94));
    border-color: var(--nutui-button-primary-disabled, var(--nutui-color-primary-disabled, #fd9d94));
}
```

### 期望的结果是什么？

primary 类型的按钮禁用时能保持渐变色，与主题色关联

### 实际的结果是什么？

primary 类型的按钮禁用时只有一种色值，且与主题色不符
